---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/dotfiles.yml
      tags:
        - debug
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/brew-prep.yml
    - include_role:
        name: geerlingguy.homebrew
    - include_tasks: tasks/extra-packages.yml
    - include_tasks: tasks/dock.yml