---
- file:
    path: "~/{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - ".aws"

- name: Copy .ssh
  copy:
    src: ".ssh"
    dest: "~"
    mode: 0600

- name: Copy github
  copy:
    src: "github"
    dest: "~/Desktop"

- name: Copy config for work
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .bash_profile
    - .bashrc
    - .saml2aws
    - .gitconfig